export type { Unit, LiftKey, LiftCategory, WeekNumber, TemplateKey, SetKind, WorkingSet } from './types';

export { roundToIncrement } from './rounding';
export { computeTrainingMax } from './trainingMax';
export { estimate1RM } from './estimate';
export { generateMainSets, generateWarmups, generateSupplemental } from './sets';
export { computePlates } from './plates';
export { suggestProgression } from './progression';
export type { ProgressionInput, ProgressionDecision, ProgressionResult } from './progression';
export { buildWorkout } from './workout';
export type { WorkoutParams } from './workout';
export { nextUp, LIFT_ORDER } from './schedule';
export type { LoggedSession } from './schedule';
export { orderedLifts, moveItem } from './liftOrder';
export { estimatedOneRmSeries, trainingMaxSeries, personalRecord, cycleLog } from './history';
export type { OneRmPoint, TmPoint, PR, CycleLogEntry, CycleLogGroup } from './history';
export { EXERCISE_DEMOS, getExerciseDemo } from './exercises';
export type { ExerciseDemo } from './exercises';
export { bodyweightSeries, latestWeight, bodyweightAxis } from './bodyweight';
export { ASSISTANCE_CATALOG, exerciseOptions } from './assistanceCatalog';
export { SUPPORTING_CATALOG, categoriesForLift, bbbFor, supportingList } from './supportingCatalog';
export type { SupportingItem } from './supportingCatalog';
export { aggregateSupportingHistory } from './supportingHistory';
export type { SupportingExerciseHistory } from './supportingHistory';
